# Generated by Django 5.2.7 on 2025-10-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Usuário'), ('bot', 'Bot')], max_length=10),
        ),
    ]
